//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEasy.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexColumnName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexColumnName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMEasy.Resource.IndexColumnName", typeof(IndexColumnName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string IX_AccountNumber {
            get {
                return ResourceManager.GetString("IX_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string IX_Barcode {
            get {
                return ResourceManager.GetString("IX_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Location Code.
        /// </summary>
        public static string IX_BinCode {
            get {
                return ResourceManager.GetString("IX_BinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Code.
        /// </summary>
        public static string IX_BrandCode {
            get {
                return ResourceManager.GetString("IX_BrandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Name.
        /// </summary>
        public static string IX_BusinessTypeName {
            get {
                return ResourceManager.GetString("IX_BusinessTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        public static string IX_CardNo {
            get {
                return ResourceManager.GetString("IX_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string IX_ClientName {
            get {
                return ResourceManager.GetString("IX_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string IX_CodeName {
            get {
                return ResourceManager.GetString("IX_CodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string IX_CountryCode {
            get {
                return ResourceManager.GetString("IX_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method Name.
        /// </summary>
        public static string IX_DeliveryMethodName {
            get {
                return ResourceManager.GetString("IX_DeliveryMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        public static string IX_DepartmentCode {
            get {
                return ResourceManager.GetString("IX_DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Name.
        /// </summary>
        public static string IX_DesignationName {
            get {
                return ResourceManager.GetString("IX_DesignationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string IX_Email {
            get {
                return ResourceManager.GetString("IX_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Days.
        /// </summary>
        public static string IX_InterestDay {
            get {
                return ResourceManager.GetString("IX_InterestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Description.
        /// </summary>
        public static string IX_LongDescription {
            get {
                return ResourceManager.GetString("IX_LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group Code.
        /// </summary>
        public static string IX_ProductGroupCode {
            get {
                return ResourceManager.GetString("IX_ProductGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string IX_RegistrationNumber {
            get {
                return ResourceManager.GetString("IX_RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string IX_RoleName {
            get {
                return ResourceManager.GetString("IX_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Code.
        /// </summary>
        public static string IX_SectionCode {
            get {
                return ResourceManager.GetString("IX_SectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string IX_ShortDescription {
            get {
                return ResourceManager.GetString("IX_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        public static string IX_StoreName {
            get {
                return ResourceManager.GetString("IX_StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Category Name.
        /// </summary>
        public static string IX_SupplierCategoryName {
            get {
                return ResourceManager.GetString("IX_SupplierCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Group Name.
        /// </summary>
        public static string IX_SupplierGroupName {
            get {
                return ResourceManager.GetString("IX_SupplierGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX / VAT Code.
        /// </summary>
        public static string IX_TaxName {
            get {
                return ResourceManager.GetString("IX_TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure.
        /// </summary>
        public static string IX_UnitofMeasure {
            get {
                return ResourceManager.GetString("IX_UnitofMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string IX_UserName {
            get {
                return ResourceManager.GetString("IX_UserName", resourceCulture);
            }
        }
    }
}
