//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xen.Resources.Properties.StatusMessageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatusMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xen.Resources.Properties.StatusMessageResources.StatusMessageResource", typeof(StatusMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was added..
        /// </summary>
        public static string DataAdded {
            get {
                return ResourceManager.GetString("DataAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested  information already exists..
        /// </summary>
        public static string DataAlreadyExists {
            get {
                return ResourceManager.GetString("DataAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Context is Change.
        /// </summary>
        public static string DatabaseContextChange {
            get {
                return ResourceManager.GetString("DatabaseContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Not Connected.
        /// </summary>
        public static string DataBaseNotConnected {
            get {
                return ResourceManager.GetString("DataBaseNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Operation Failed.
        /// </summary>
        public static string DatabaseOperationFailed {
            get {
                return ResourceManager.GetString("DatabaseOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information has been updated by another user, your version is not the current..
        /// </summary>
        public static string DataCollisionExists {
            get {
                return ResourceManager.GetString("DataCollisionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was copied..
        /// </summary>
        public static string DataCopied {
            get {
                return ResourceManager.GetString("DataCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was deactivated..
        /// </summary>
        public static string DataDeactivated {
            get {
                return ResourceManager.GetString("DataDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was deleted..
        /// </summary>
        public static string DataDeleted {
            get {
                return ResourceManager.GetString("DataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information does not exist..
        /// </summary>
        public static string DataDoesNotExist {
            get {
                return ResourceManager.GetString("DataDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information exists..
        /// </summary>
        public static string DataExists {
            get {
                return ResourceManager.GetString("DataExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information has been generated..
        /// </summary>
        public static string DataGenerated {
            get {
                return ResourceManager.GetString("DataGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requeted information is in use..
        /// </summary>
        public static string DataIsBeingUsed {
            get {
                return ResourceManager.GetString("DataIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information may be deactivated..
        /// </summary>
        public static string DataIsDeactivatable {
            get {
                return ResourceManager.GetString("DataIsDeactivatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information is not in use..
        /// </summary>
        public static string DataIsNotBeingUsed {
            get {
                return ResourceManager.GetString("DataIsNotBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information is not valid..
        /// </summary>
        public static string DataIsNotValid {
            get {
                return ResourceManager.GetString("DataIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information is valid..
        /// </summary>
        public static string DataIsValid {
            get {
                return ResourceManager.GetString("DataIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was not added..
        /// </summary>
        public static string DataNotAdded {
            get {
                return ResourceManager.GetString("DataNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was not deactivated..
        /// </summary>
        public static string DataNotDeactivated {
            get {
                return ResourceManager.GetString("DataNotDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information is in use..
        /// </summary>
        public static string DataNotDeleted {
            get {
                return ResourceManager.GetString("DataNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was not updated..
        /// </summary>
        public static string DataNotUpdated {
            get {
                return ResourceManager.GetString("DataNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was not validated..
        /// </summary>
        public static string DataNotValidated {
            get {
                return ResourceManager.GetString("DataNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information partially exists..
        /// </summary>
        public static string DataPartiallyExists {
            get {
                return ResourceManager.GetString("DataPartiallyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information is pending for approval..
        /// </summary>
        public static string DataPendingForApproval {
            get {
                return ResourceManager.GetString("DataPendingForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been queued..
        /// </summary>
        public static string DataQueued {
            get {
                return ResourceManager.GetString("DataQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information was updated..
        /// </summary>
        public static string DataUpdated {
            get {
                return ResourceManager.GetString("DataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Exists.
        /// </summary>
        public static string ExceptionExists {
            get {
                return ResourceManager.GetString("ExceptionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username or Password you entered is incorrect..
        /// </summary>
        public static string Invaliddata {
            get {
                return ResourceManager.GetString("Invaliddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name or Password..
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Succeeded.
        /// </summary>
        public static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Succeeded with Warning.
        /// </summary>
        public static string SucceedWithWarning {
            get {
                return ResourceManager.GetString("SucceedWithWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested information successfully saved.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status..
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
