//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xen.Resources.Properties.SQLErrorResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xen.Resources.Properties.SQLErrorResources.SQLError", typeof(SQLError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General database warning occurred: {0}.
        /// </summary>
        public static string SQLSTATE01000 {
            get {
                return ResourceManager.GetString("SQLSTATE01000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor operation conflict occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE01001 {
            get {
                return ResourceManager.GetString("SQLSTATE01001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL value eliminated in set function error on database operation: {0}.
        /// </summary>
        public static string SQLSTATE01003 {
            get {
                return ResourceManager.GetString("SQLSTATE01003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General database error occurred: {0}.
        /// </summary>
        public static string SQLSTATE07008 {
            get {
                return ResourceManager.GetString("SQLSTATE07008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server rejected the database connection: {0}.
        /// </summary>
        public static string SQLSTATE08004 {
            get {
                return ResourceManager.GetString("SQLSTATE08004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinality Violation occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE21000 {
            get {
                return ResourceManager.GetString("SQLSTATE21000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert value list does not match column list on database operation: {0}.
        /// </summary>
        public static string SQLSTATE21S01 {
            get {
                return ResourceManager.GetString("SQLSTATE21S01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree of derived table does not match column list: {0}.
        /// </summary>
        public static string SQLSTATE21S02 {
            get {
                return ResourceManager.GetString("SQLSTATE21S02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String data, right-truncation occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE22001 {
            get {
                return ResourceManager.GetString("SQLSTATE22001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value out of range on database operation: {0}.
        /// </summary>
        public static string SQLSTATE22003 {
            get {
                return ResourceManager.GetString("SQLSTATE22003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid datetime format on database operation: {0}.
        /// </summary>
        public static string SQLSTATE22007 {
            get {
                return ResourceManager.GetString("SQLSTATE22007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero error occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE22012 {
            get {
                return ResourceManager.GetString("SQLSTATE22012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character value for cast specification on database operation: {0}.
        /// </summary>
        public static string SQLSTATE22018 {
            get {
                return ResourceManager.GetString("SQLSTATE22018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape character occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE22019 {
            get {
                return ResourceManager.GetString("SQLSTATE22019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE22025 {
            get {
                return ResourceManager.GetString("SQLSTATE22025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity constraint violation occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE23000 {
            get {
                return ResourceManager.GetString("SQLSTATE23000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cursor state on database operation: {0}.
        /// </summary>
        public static string SQLSTATE24000 {
            get {
                return ResourceManager.GetString("SQLSTATE24000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction state on database operation: {0}.
        /// </summary>
        public static string SQLSTATE25000 {
            get {
                return ResourceManager.GetString("SQLSTATE25000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authorization specification on database operation: {0}.
        /// </summary>
        public static string SQLSTATE28000 {
            get {
                return ResourceManager.GetString("SQLSTATE28000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cursor name occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE34000 {
            get {
                return ResourceManager.GetString("SQLSTATE34000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization failure occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE40001 {
            get {
                return ResourceManager.GetString("SQLSTATE40001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error or access violation occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE42000 {
            get {
                return ResourceManager.GetString("SQLSTATE42000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base table or view already exists: {0}.
        /// </summary>
        public static string SQLSTATE42S01 {
            get {
                return ResourceManager.GetString("SQLSTATE42S01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base table or view not found: {0}.
        /// </summary>
        public static string SQLSTATE42S02 {
            get {
                return ResourceManager.GetString("SQLSTATE42S02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index already exists error occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATE42S11 {
            get {
                return ResourceManager.GetString("SQLSTATE42S11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index not found on database operation: {0}.
        /// </summary>
        public static string SQLSTATE42S12 {
            get {
                return ResourceManager.GetString("SQLSTATE42S12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column already exists: {0}.
        /// </summary>
        public static string SQLSTATE42S21 {
            get {
                return ResourceManager.GetString("SQLSTATE42S21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column not found on database operation: {0}.
        /// </summary>
        public static string SQLSTATE42S22 {
            get {
                return ResourceManager.GetString("SQLSTATE42S22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record operation could not completed because one or more fields failed data level security or data definition check.  Check with your system administrator to confirm your data security role..
        /// </summary>
        public static string SQLSTATE44000 {
            get {
                return ResourceManager.GetString("SQLSTATE44000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATEHY000 {
            get {
                return ResourceManager.GetString("SQLSTATEHY000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cursor position occurred on database operation: {0}.
        /// </summary>
        public static string SQLSTATEHY109 {
            get {
                return ResourceManager.GetString("SQLSTATEHY109", resourceCulture);
            }
        }
    }
}
